Subject.create name: "OOP"
Subject.create name: "General programming knowledge"
Subject.create name: "Data structure"
Subject.create name: "Database"
Subject.create name: "MVC"
Subject.create name: "HTTP"
Subject.create name: "Algorithm"
Subject.create name: "Ruby"
Subject.create name: "Ruby on Rails"
Subject.create name: "Java"
Subject.create name: "Javascript"
Subject.create name: "Other"
